version: "3.8"

volumes: 
    postgres-vol:

networks:
    my-own-network:

services:

    postgresql:
        image: postgres:12.4
        container_name: postgresql
        restart: unless-stopped
        healthcheck:
            test:
                [
                  "CMD-SHELL",
                  "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"
                ]
            start_period: 10s
            retries: 5
            interval: 10s
            timeout: 3s    
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: principal
            bind-address: 0.0.0.0
        ports:
            - 5432:5432
        volumes: 
            - postgres-vol:/var/lib/postgresql/data
        networks: 
            - my-own-network
