version: "3.8"

networks:
    smartschool-app-net:

services:

    smartschool:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: smartschool-app
        networks: 
            - smartschool-app-net
            - compose_my-own-network
        ports: 
            - 5000:80
        environment: 
            - DBHOST=postgresql
        depends_on: 
            - postgresql